name: Deploy CRM Web

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/crm-web

            git reset --hard
            git clean -fd

            git pull origin develop

            npm install
            npm run build

            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r dist/* /usr/share/nginx/html/

            sudo nginx -t
            sudo systemctl restart nginx
